### ISSUE TITLE
Funcionalidade importante: Todos os nós devem ter mais de um pino de saída (mais de um link).

### ISSUE THREAD

**Issue by alexbprr** [Syndelis/ode-designer#12]

**Comment by Syndelis** [comment]
Conversei com você em chamada @alexbprr, mas vou deixar aqui para que o @Diegovsky e o @S-Pz possam ver também:

## O problema

Populações devem conseguir se ligar a mais de um combinador, porque podem aparecer em mais de um componente de equação.

Exemplo (predador-presa):
- dH/dt = r.H - a.H.P

No exemplo, `r.H` é o componente de reprodução (um nó combinatório) e `a.H.P` é outro. Assim, o nó população `H` precisa, de alguma forma, se ligar a dois componentes diferentes.

## As _possíveis_ soluções

Eu vejo 3 saídas (mutualmente exclusivas) para este problema:

1. Permitimos que o **único** pino de saída destes nós mencionados se liguem a mais de um pino de entrada. Não existe nada na lógica do código que impeça isso no momento, o único impeditivo é que clicar com o botão esquerdo em cima de um link excluí-lo-ia;
2. Podemos fazer com que os nós de saída se repliquem sempre que forem utilizados, assim como funcionam os nós de entrada da população e do combinatório. O único problema que vejo com essa abordagem é replicar esse código para todos os nós que precisam dessa lógica;
3. Adicionar um novo nó "multiplexador", que, a partir de uma entrada, gera múltiplos pinos de saída. A complicação dessa abordagem é que os nós multiplexadores receberiam o resultado da equação do combinatório e teriam que repassar para a população, mas fora isso não deve ser difícil de implementar;
