### ISSUE TITLE
Funcionalidade importante: Implementação da caixa de seleção nos nós do tipo Population para a escolha dos termos da EDO da população.

### ISSUE THREAD

**Issue by alexbprr** [Syndelis/ode-designer#15]
**Importante**: O nome da população não deve ser gerado dentro do nó dela para as ligações de saída (pins de saída) como é feito atualmente. 
**Dentro do nó population, só aparece a condição inicial e os termos da população.** 

Um termo (presente em um combinator) poderá ser adicionado com um botão + ao lado da caixa seletora. Após adicionado, cada termo terá um - para ser removido.

**Comment by Syndelis** [comment]
Concluído
