### ISSUE TITLE
Implementação de funcionalidades básicas para melhorar a interface (Ações: Remoção de nós e links, criação de nós. )

### ISSUE THREAD

**Issue by alexbprr** [Syndelis/ode-designer#8]
Menu de Contexto (botão direito) de ações de um nó: 

- Remoção de nós; 

Menu de Contexto (botão direito) de ações de um link: 

- Remoção de links; 

Outra funcionalidade: 

- Criar o nó no local apontado pelo mouse.

**Comment by Syndelis** [comment]
Concluído
